### ISSUE TITLE
Parallel actor creation can deadlock or crash riker

### ISSUE THREAD

**Issue by hardliner66** [riker-rs/riker#122]
While implementing one of the benchmarks from [actor-framework/benchmarks](https://github.com/actor-framework/benchmarks), I found out that riker sometims deadlocks (hangs) or crashes with an access violation when multiple actors get created simultaneously.

I created a minimal example at [my test repo](https://github.com/hardliner66/riker_bench/tree/access_violation).

The problem seems to be an atomic_load in dashmap, but I'm not sure if this is a bug in dashmap or just misuse on our side.

-----
Tested on:
- Windows 10 (stable-x86_64-pc-windows-msvc 1.44.1)
- Ubuntu 20.04 LTS (stable-x86_64-unknown-linux-gnu 1.44.1)

Additional files:
[stacktrace.txt](https://github.com/riker-rs/riker/files/4854043/stack_trace.txt)

**Comment by leenozara** [comment]
@xacrimon I wonder if you're able to provide some insight into this?

**Comment by xacrimon** [comment]
Known bug in rc5, updating to rc6 should solve the issue.

**Comment by hardliner66** [comment]
I think I tested with RC6 too. I will retry with an updated version of dashmap and report my findings.

**Comment by xacrimon** [comment]
This is interesting, it hasn't shown up in any of the intensive multicore tests I've done.

**Comment by hardliner66** [comment]
I locally changed the version to rc6 and the problem still persists:
[build_and_run.txt](https://github.com/riker-rs/riker/files/4857917/build_and_run.txt)

**Comment by xacrimon** [comment]
I will investigate this issue. Thanks

**Comment by xacrimon** [comment]
So I got the issue. I am currently doing a major refactor that will fix this but in the meantime switching to dashmap 3.11 should do the trick.

**Comment by hardliner66** [comment]
There are some incompatible changes between 4.0 and 3.11; `Iter` needs more type parameters in 3.11 and the replace method doesn't exist. I looked at replacements (e.g.: delete and insert) but the documented locking behaviour doesn't seem to be a good fit riker.
